### ISSUE TITLE
Issue #02 - MVP List 

### ISSUE THREAD

**Issue by keginzburg** [MIFUNEKINSKi/AuteurFlix#2]
# MVP List
- [X] Should have 7 MVPs.
  - [X] 3 of those are User Auth, Heroku, and Production README.
  - [X] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [X] Includes two to three detailed bullets on functionality and presentation of feature
- [X] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [X] Estimates how long it will take the code each MVP
- [X] Correctly formatted
  - [X] MVPs are listed in an ordered list
  - [X] Each MVP is broken down into bullet points

## Comments
Be sure to make the necessary changes we discussed yesterday along with a retitling of this design document as it is currently listed as your Database Schema.
Please add a brief summary of your clone along with what it is based on and the relevant MVPs.
Production README should only take 0.5 days, so that gives you a full day to allocate to your schedule? Consider where that might go.

1. Splash/Auth 
    1. Will you give the option to Sign In Users after they Sign Up, or just a Demo User Sign In option? It’s recommended that for User Auth there are three available options: Sign In, Sign Up, and Demo Login.
    2. After user authentication, will AuteurFlix take users directly to the movie selection page or profile selection page first?
2. Browse and Play Videos
    1. Will there be profile/account settings, logout, title show page functionality on your Browse page?
3. MyList
    1. MyList technically counts as Update as well, so that’s another full CRUD cycle for your MVPs.
4. Bonuses
    1. Have you considered adding any bonus MVPs? Maybe Like/Disliking titles or an Account Payment Demo?

**Comment by MIFUNEKINSKi** [comment]
Thank you Kyle! Will work on it tonight and tomorrow

-Chris

**Comment by keginzburg** [comment]
Looks good.
