### ISSUE TITLE
Issue #03 - Schema

### ISSUE THREAD

**Issue by keginzburg** [MIFUNEKINSKi/AuteurFlix#3]
Profiles
# Database Schema
- [X] Contains correct datatypes
- [X] Contains appropriate constraints/details
  - [X] primary key
  - [X] not null
  - [X] unique
  - [X] indexed
  - [X] foreign key
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [X] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [X] Correctly formatted
  - [X] schema is written in a table format
  - [X] the table’s name are lowercased, snake_cased and `back_ticked`
  - [X] the table header column names are bolded
  - [X] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
Profiles
1. Specify which tables this table’s foreign keys refer to.
2. Timestamps?

My_Auteur_List

1. TImestamps?
2. Add a unique indexing for the pair of your profile_id and auteur_flix_id, so a user can’t add it to their list more than once.
3. Specify which tables this table’s foreign keys refer to.

Auteur_flix

1. Timestamps?
2. Length of film as a row?
3. Is decade necessary? Somewhat redundant since we have the year. If you are planning on using this to curate categories by decade, I’d maybe make this that category’s string name rather than an integer (I.e. genre ⇒ ‘Horror’ vs decade ⇒ 1960). Could be fun coming up with specific decade genre names. Could do this as a string in this table or a separate genre table.
4. Also, following up on that: genres? And if so, will films have multiple genres?

**Comment by MIFUNEKINSKi** [comment]
Auteur_flix
1) removed decade for redundancy, will use year for decade
2) plan on 2 categories, decade and by director

**Comment by keginzburg** [comment]
Be sure to add timestamps to all tables. Also, you might need to add some basic tables for director and decade down the line. For now though, this looks good.
