### ISSUE TITLE
Issue #05 - Backend Routes

### ISSUE THREAD

**Issue by keginzburg** [MIFUNEKINSKi/AuteurFlix#5]
# Backend Routes
- [X] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [X] API Endpoint routes contains wildcard variables written in `snake_case`
- [X] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [X] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn’t need a `GET likes` api endpoint because that info comes through the post show

## Comments
Down the line, please add more descriptive bullets for each backend routes info. If you add genres, add those backend routes as well.

For users:

1. Do we want to potentially have routes so Users can update or delete their account?

For auteur_flix:

1.  Correct the dash to an underscore.
2. Do we want a route to pull all of our films from the backend, or just a singular route to pull individual films (one at a time)?
3. Also, will we potentially need a custom route when searching for a film? What could we utilize in this custom route?

**Comment by MIFUNEKINSKi** [comment]
added individual movies and all movie routes.  & custom route for search

**Comment by keginzburg** [comment]
Looks good. You'll refer to this document a lot down the line, so be sure to continue updating it if need be as you go.
