### ISSUE TITLE
Issue #06 - Frontend Routes & Components

### ISSUE THREAD

**Issue by keginzburg** [MIFUNEKINSKi/AuteurFlix#6]
# Frontend Routes
- [X] Frontend routes contains wildcard variables written in `camelCase`
- [ ] Correctly formatted
  - [X] Routes are displayed with `inline coding text` (backticks)

## Comments
Please specify which routes and components will be accessible whether or not a user is logged in, logged out, or if that doesn’t apply.

1. Do we want a /signup route and SignUpForm component for that?
2. Formatting might be off for your /search frontend route. Also is this technically a frontend route that we want to highlight here? Does this route to a Search Component? Or do we want to just make a search query string available anytime the user interacts with the search bar in our NavBar component?
3. Any IndexItem components?
4. Any modals?

**Comment by MIFUNEKINSKi** [comment]
1. Signup will be on the splash page as a modal
2. Will remove, not a component

**Comment by keginzburg** [comment]
Once these are dealt with, you should be good with this design document.
